# Numba/llvmlite stack needs an older compiler for backwards compatibility.
# Numba/llvmlite stack needs an older compiler for backwards compatability.
c_compiler_version:
  - 7                       # [linux and (x86_64 or ppc64le)]
  - 9                       # [linux and aarch64]
  - 14                      # [osx]

cxx_compiler_version:
  - 7                       # [linux and (x86_64 or ppc64le)]
  - 9                       # [linux and aarch64]
  - 14                      # [osx]

fortran_compiler_version:
  - 7                       # [linux and (x86_64 or ppc64le)]
  - 9                       # [linux and aarch64]

cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
