# --- Compilers ---
c_compiler_version:
  - 9                       # [linux]
  - 14                      # [osx]

cxx_compiler_version:
  - 9                       # [linux]
  - 14                      # [osx]

fortran_compiler_version:
  - 9                       # [linux]

cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]

# Sysroots for compatibility on Linux builds.
sysroot_linux_64:
  - 2.17             # [linux64]

sysroot_linux_aarch64:
  - 2.17             # [aarch64]

# --- MACOS DEPLOYMENT TARGET ---
# Sets minimum OS version to Big Sur (11.0) for Mac builds.
MACOSX_DEPLOYMENT_TARGET:
  - 11.0             # [osx]

# --- MACOS SDK ---
# We use a newer SDK (e.g. 11.3) to build, even if targeting 11.0
MACOSX_SDK_VERSION:
  - 11.3             # [osx]
