c_compiler_version:
  - 9                       # [linux]
  - 14                      # [osx]

cxx_compiler_version:
  - 9                       # [linux]
  - 14                      # [osx]

fortran_compiler_version:
  - 9                       # [linux]

cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
